sudo: required
language: cpp

matrix:
  include:
    # We need to use Ubuntu Xenial to upgrade pip.
    - os: linux
      dist: xenial
      compiler: clang
      env:
        - BUILD_TYPE=Debug
        - CXXFLAGS='-D_GLIBCXX_USE_CXX11_ABI=1'
        - LIBCXX=libstdc++11
    - os: linux
      dist: xenial
      compiler: clang
      env:
        - BUILD_TYPE=Release
        - CXXFLAGS='-D_GLIBCXX_USE_CXX11_ABI=1'
        - LIBCXX=libstdc++11
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
        - CXXFLAGS='-D_GLIBCXX_USE_CXX11_ABI=1'
        - LIBCXX=libstdc++11
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        - BUILD_TYPE=Release
        - CXXFLAGS='-D_GLIBCXX_USE_CXX11_ABI=1'
        - LIBCXX=libstdc++11
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=Debug
        - LIBCXX=libc++
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=Release
        - LIBCXX=libc++
    # GCC on OSX is just a wrapper for Clang.

install:
  # The root environment on Travis does not have cmake on its PATH.
  # https://github.com/travis-ci/travis-ci/issues/9113#issuecomment-366448032
  - curl --location https://raw.githubusercontent.com/thejohnfreeman/cmake-future/master/install.sh | sudo env "PATH=$PATH" bash
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade conan --ignore-installed
  - conan user
  - conan --version
  - conan remote list
  - cmake --version

script:
  - mkdir build
  - cd build
  - conan install
    --setting "compiler.libcxx=$LIBCXX"
    --setting "build_type=$BUILD_TYPE"
    --build missing
    ..
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - cmake --build . --config ${BUILD_TYPE} --parallel $(nproc)
  - ctest --build-config $BUILD_TYPE --verbose --parallel $(nproc)
