sudo: required
language: cpp

.xenial: &xenial
  os: linux
  dist: xenial
  addons:
    apt:
      sources:
        - deadsnakes
      packages:
        - python3.6-dev
  before_install:
    - curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6

matrix:
  include:
    # We need to use Ubuntu Xenial to upgrade pip.
    - <<: *xenial
      compiler: clang
      env:
        - BUILD_TYPE=debug
        - CONAN_ENV_COMPILER_LIBCXX=libstdc++11
        - CXXFLAGS='-D_GLIBCXX_USE_CXX11_ABI=1'
    - <<: *xenial
      compiler: clang
      env:
        - BUILD_TYPE=release
        - CONAN_ENV_COMPILER_LIBCXX=libstdc++11
        - CXXFLAGS='-D_GLIBCXX_USE_CXX11_ABI=1'
    - <<: *xenial
      compiler: gcc
      env:
        - BUILD_TYPE=debug
        - CONAN_ENV_COMPILER_LIBCXX=libstdc++11
        - CXXFLAGS='-D_GLIBCXX_USE_CXX11_ABI=1'
    - <<: *xenial
      compiler: gcc
      env:
        - BUILD_TYPE=release
        - CONAN_ENV_COMPILER_LIBCXX=libstdc++11
        - CXXFLAGS='-D_GLIBCXX_USE_CXX11_ABI=1'
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=debug
        - CONAN_ENV_COMPILER_LIBCXX=libc++
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=release
        - CONAN_ENV_COMPILER_LIBCXX=libc++
    # GCC on OSX is just a wrapper for Clang.

addons:
  homebrew:
    packages:
      - cmake
    update: true

install:
  # The root environment on Travis does not have cmake on its PATH.
  # https://github.com/travis-ci/travis-ci/issues/9113#issuecomment-366448032
  - curl --location https://raw.githubusercontent.com/thejohnfreeman/cmake-future/master/install.sh | sudo env "PATH=$PATH" bash
  - sudo pip3 install --upgrade pip
  - sudo pip3 install --upgrade conan cupcake --ignore-installed
  - conan user
  - conan --version
  - conan remote list
  - cmake --version
  - cupcake --version

script:
  - cupcake configure --${BUILD_TYPE} --generator 'Unix Makefiles'
  - cupcake test --${BUILD_TYPE}
