if(INCLUDED_CUPCAKE)
  return()
endif()
set(INCLUDED_CUPCAKE TRUE CACHE INTERNAL "")

include(cupcake_project)
include(cupcake_find_package)
include(cupcake_find_conan_packages)
include(cupcake_add_subproject)
include(cupcake_add_library)
include(cupcake_add_executable)
include(cupcake_add_test_executable)
include(cupcake_add_tests)
include(cupcake_install_project)
include(cupcake_install_cpp_info)
