name: install Windows environment
description: |
  Install the common environment shared by all jobs in the windows workflow.
inputs:
  cache-key-scoop:
    required: true
  cache-key-python:
    required: true
runs:
  using: composite
  steps:
    - name: read environment
      id: env
      shell: pwsh
      run: |
        echo "PROGRAMDATA=%PROGRAMDATA%" >> $GITHUB_OUTPUT
        echo "USERPROFILE=%USERPROFILE%" >> $GITHUB_OUTPUT
    - name: install Make from cache
      id: cache-scoop
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.env.outputs.PROGRAMDATA }}\scoop
          ${{ steps.env.outputs.USERPROFILE }}\scoop
        key: ${{ inputs.cache-key-scoop }}
    - name: install Make with Scoop
      if: steps.cache-scoop.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        iwr -useb get.scoop.sh -outfile install.ps1
        .\install.ps1 -RunAsAdmin
        rm install.ps1
        scoop install make
    - name: install Python packages
      uses: ./.github/actions/install-python
      with:
        key: ${{ inputs.cache-key-python }}
    - name: check environment
      shell: pwsh
      run: |
        $env:PATH -split ';'
        python --version
        conan --version
        cmake --version
        cupcake --version
        dir env:
