name: install Windows environment
description: |
  Install the common environment shared by all jobs in the windows workflow.
inputs:
  cache-key-scoop:
    required: true
  cache-key-python:
    required: true
runs:
  using: composite
  steps:
    - name: read environment
      id: env
      shell: pwsh
      run: |
        echo "::set-output name=PROGRAMDATA::%PROGRAMDATA%"
        echo "::set-output name=USERPROFILE::%USERPROFILE%"
    - name: install Make from cache
      id: cache-scoop
      uses: actions/cache@v2
      with:
        path: |
          ${{ steps.env.outputs.PROGRAMDATA }}\scoop
          ${{ steps.env.outputs.USERPROFILE }}\scoop
        key: ${{ inputs.cache-key-scoop }}
    - name: install Make with Scoop
      if: steps.cache-scoop.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        iwr -useb get.scoop.sh | iex
        scoop install make
    - name: install Python packages
      uses: ./.github/actions/install-python
      with:
        key: ${{ inputs.cache-key-python }}
    - name: check environment
      shell: pwsh
      run: |
        $env:PATH -split ';'
        python --version
        conan --version
        cmake --version
        make --version
        dir env:
