name: install Windows environment
description: |
  Install the common environment shared by all jobs in the windows workflow.
inputs:
  cache-key-scoop:
    required: true
  cache-key-python:
    required: true
runs:
  using: composite
  steps:
    - name: read environment
      id: env
      shell: pwsh
      run: |
        echo "::set-output name=PROGRAMDATA::%PROGRAMDATA%"
        echo "::set-output name=USERPROFILE::%USERPROFILE%"
    - name: install Make from cache
      id: cache-scoop
      uses: actions/cache@v2
      with:
          path: |
            ${{ steps.env.outputs.PROGRAMDATA }}\scoop
            ${{ steps.env.outputs.USERPROFILE }}\scoop
          key: ${{ inputs.cache-key-scoop }}
    - name: install Make with Scoop
      if: steps.cache-scoop.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        iwr -useb get.scoop.sh | iex
        scoop install make
    - name: download Conan from cache
      id: cache-python
      uses: actions/cache@v2
      with:
          path: .cache-python
          key: ${{ inputs.cache-key-python }}
    - name: download Conan with pip
      if: steps.cache-python.outputs.cache-hit != 'true'
      shell: pwsh
      run: pip download conan --dest .cache-python
    - name: install Conan
      shell: pwsh
      run: pip install conan --no-index --find-links .cache-python
    - name: check environment
      shell: pwsh
      run: |
        $env:PATH -split ';'
        python --version
        conan --version
        cmake --version
        make --version
        dir env:
