name: install Python packages
description: |
  Install the common Python packages shared by all jobs.
inputs:
  key:
    required: true
  shell:
    default: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
runs:
  using: composite
  steps:
    - name: debug
      shell: bash
      run: echo shell = "${{ inputs.shell }}"
    - name: learn Python cache directory
      id: pip-cache
      shell: bash
      run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
    - name: restore Python cache directory
      id: cache
      uses: actions/cache@v2
      with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ inputs.key }}
    - name: install Conan
      shell: bash
      run: pip install wheel 'conan<2' poetry cupcake
