name: install Python packages
description: |
  Install the common Python packages shared by all jobs.
inputs:
  key:
    required: true
  shell:
    default: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
runs:
  using: composite
  steps:
    - name: install Python
      uses: actions/setup-python@v5
      with:
        # The `imp` module is removed in Python 3.12
        # but required by Conan 1.x.
        python-version: '3.11'
        cache: pip
        cache-dependency-path: .github/workflows/cache-python
    - name: learn Python cache directory
      id: pip-cache
      shell: bash
      run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
    - name: restore Python cache directory
      id: cache
      uses: actions/cache@v4
      with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ inputs.key }}
    - name: install Conan
      shell: bash
      run: |
        venv=${HOME}/.venvs/conan
        python -m venv ${venv}
        ls -d ${HOME}/.venvs
        ls -l ${HOME}/.venvs
        ls -l ${venv}
        ls -l ${venv}/bin
        ${venv}/bin/pip install --upgrade pip
        ${venv}/bin/pip install 'conan<2'
        ${venv}/bin/conan --version
        mkdir -p ${HOME}/.local/bin
        ln ${venv}/bin/conan ${HOME}/.local/bin/conan
        echo ${HOME}/.local/bin >> ${GITHUB_PATH}
    - name: check installation
      shell: bash
      run: |
        type conan
        conan --version
    - name: install packages
      shell: bash
      run: |
        pip install --upgrade pip
        pip install poetry cupcake
    - name: configure Conan
      shell: bash
      run: |
        conan profile new default --detect
