name: install Python packages
description: |
  Install the common Python packages shared by all jobs.
inputs:
  key:
    required: true
  shell:
    default: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
runs:
  using: composite
  steps:
    - name: install Python
      uses: actions/setup-python@v4
      with:
        # The `imp` module is removed in Python 3.12
        # but required by Conan 1.x.
        python-version: '3.11'
        cache: pip
        cache-dependency-path: .github/workflows/cache-python
    - name: learn Python cache directory
      id: pip-cache
      shell: bash
      run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
    - name: restore Python cache directory
      id: cache
      uses: actions/cache@v2
      with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ inputs.key }}
    - name: install packages
      shell: bash
      run: |
        pip install --upgrade pip
        pip install wheel 'conan<2' poetry 'cupcake>=0.2'
    - name: configure Conan
      shell: bash
      run: |
        conan profile new default --detect
