set_property(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
  PROPERTY PROJECT_NAME ${PROJECT_NAME}
)
set_property(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
  PROPERTY PROJECT_VERSION ${PROJECT_VERSION}
)
set_property(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
  PROPERTY PROJECT_VERSION_MAJOR ${PROJECT_VERSION_MAJOR}
)
set_property(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
  PROPERTY PROJECT_VERSION_MINOR ${PROJECT_VERSION_MINOR}
)
set_property(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
  PROPERTY PROJECT_VERSION_PATCH ${PROJECT_VERSION_PATCH}
)
