name: Build and test on Linux
on: [push, pull_request]

jobs:
  job:
    runs-on: ubuntu-18.04
    steps:
      - name: install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: install environment
        run: |
          pip install conan
          python --version
          conan --version
          cmake --version
          gcc --version
          conan remote add jfreeman https://api.bintray.com/conan/jfreeman/jfreeman
      - name: checkout
        uses: actions/checkout@v2
      - name: configure
        run: |
          mkdir build
          mkdir --parents install/lib/cmake
          cd build
          conan install .. --build missing
          cmake \
            -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake \
            -DCMAKE_INSTALL_PREFIX=$PWD/../install \
            ..
      - name: build
        run: cmake --build build
      - name: test
        run: cmake --build build --target test
      - name: install
        run: cmake --build build --target install
      - name: configure example
        run: |
          cd examples/english
          mkdir build
          mkdir --parents install/lib/cmake
          cd build
          conan install .. --build missing
          cmake \
            -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake \
            -DCMAKE_INSTALL_PREFIX=$PWD/../install \
            -DCMAKE_PREFIX_PATH=$PWD/../../../install \
            ..
      - name: build example
        run: cmake --build examples/english/build
      - name: test example
        run: [ "$(examples/english/build/main)" == "hello, world!" ]
