name: Build and test on Linux
on: [push, pull_request]

jobs:
  job:
    runs-on: ubuntu-18.04
    steps:
      - name: install environment
        run: |
          gcc --version
          clang --version
          python --version
          cmake --version
          pip install --upgrade pip
          pip install conan
          conan --version
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          mkdir build
          cd build
          conan install .. --build missing
          cmake -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake -DCMAKE_INSTALL_PREFIX=$PWD/../install ..
          cmake --build .
          ctest .
