name: nix-direct
on:
  workflow_run:
    workflows: [nix-upstream]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  _05-fetch-content:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        platform:
          - ubuntu
          - macos
        generator:
          - { name: Ninja, multi: false }
          - { name: Unix Makefiles, multi: false }
        shared:
          - ON
          - OFF
        flavor:
          - Debug
          - Release
    runs-on: ${{ matrix.platform }}-latest
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: /usr/local
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: export cupcake
        uses: ./.github/actions/export-cupcake
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 05-fetch-content
          executable: five

  _08-find-module:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        platform:
          - ubuntu
          - macos
        generator:
          - { name: Ninja, multi: false }
          - { name: Unix Makefiles, multi: false }
        shared:
          - ON
          - OFF
        flavor:
          - Debug
          - Release
    runs-on: ${{ matrix.platform }}-latest
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: /usr/local
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: export cupcake
        uses: ./.github/actions/export-cupcake
      - name: install zero
        working-directory: 00-upstream
        run: |
          make build
          sudo install_dir="${install_dir}" make install
          make clean
      - name: remove zero package configuration file
        run: sudo rm -rf ${install_dir}/share/zero
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 08-find-module
          executable: eight

  _09-external-project:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        platform:
          - ubuntu
          - macos
        generator:
          - { name: Ninja, multi: false }
          - { name: Unix Makefiles, multi: false }
        shared:
          - ON
          - OFF
        flavor:
          - Debug
          - Release
    runs-on: ${{ matrix.platform }}-latest
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: /usr/local
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: export cupcake
        uses: ./.github/actions/export-cupcake
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 09-external-project
          executable: nine

  _10-conan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        platform:
          - ubuntu
          - macos
        generator:
          - { name: Ninja, multi: false }
          - { name: Unix Makefiles, multi: false }
        shared:
          - ON
          - OFF
        flavor:
          - Debug
          - Release
    runs-on: ${{ matrix.platform }}-latest
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: /usr/local
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: export cupcake
        uses: ./.github/actions/export-cupcake
      - name: export zero
        working-directory: 00-upstream
        run: conan create .
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 10-conan
          executable: ten

  _11-no-cupcake:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        platform:
          - ubuntu
          - macos
        generator:
          - { name: Ninja, multi: false }
          - { name: Unix Makefiles, multi: false }
        shared:
          - ON
          - OFF
        flavor:
          - Debug
          - Release
    runs-on: ${{ matrix.platform }}-latest
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: /usr/local
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: export cupcake
        uses: ./.github/actions/export-cupcake
      - name: install zero
        working-directory: 00-upstream
        run: |
          make build
          sudo install_dir="${install_dir}" make install
          make clean
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 11-no-cupcake
          executable: eleven
