name: Build, run, test, and install on Linux and MacOS
on: [push, pull_request]

jobs:
  zero:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        generator:
          - { name: Ninja, multi: false }
          - { name: Unix Makefiles, multi: false }
        shared:
          - ON
          - OFF
        flavor:
          - Debug
          - Release
    runs-on: ${{ matrix.platform }}
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: /usr/local
      executable: 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 00-upstream

  one:
    needs: zero
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        generator:
          - { name: Ninja, multi: false }
          - { name: Unix Makefiles, multi: false }
        shared:
          - ON
          - OFF
        flavor:
          - Debug
          - Release
    runs-on: ${{ matrix.platform }}
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: /usr/local
      executable: hello
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install zero
        working-directory: 00-upstream
        run: |
          make build
          sudo install_dir="${install_dir}" make install
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 01-find-package

  two:
    needs: zero
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        generator:
          - { name: Ninja, multi: false }
          - { name: Unix Makefiles, multi: false }
        shared:
          - ON
          - OFF
        flavor:
          - Debug
          - Release
    runs-on: ${{ matrix.platform }}
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: /usr/local
      executable: goodbye
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: copy zero
        run: |
          cp -r 00-upstream 02-add-subdirectory/external
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 02-add-subdirectory

  three:
    needs: one
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        generator:
          - { name: Ninja, multi: false }
          - { name: Unix Makefiles, multi: false }
        shared:
          - ON
          - OFF
        flavor:
          - Debug
          - Release
    runs-on: ${{ matrix.platform }}
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: /usr/local
      executable: aloha
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install zero
        working-directory: 00-upstream
        run: |
          make build
          sudo install_dir="${install_dir}" make install
          make clean
      - name: install one
        working-directory: 01-find-package
        run: |
          make build
          sudo install_dir="${install_dir}" make install
          make clean
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 03-fp-fp

  four:
    needs: two
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        generator:
          - { name: Ninja, multi: false }
          - { name: Unix Makefiles, multi: false }
        shared:
          - ON
          - OFF
        flavor:
          - Debug
          - Release
    runs-on: ${{ matrix.platform }}
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: /usr/local
      executable: four
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: copy zero
        run: |
          cp -r 00-upstream 02-add-subdirectory/external
      - name: install two
        working-directory: 02-add-subdirectory
        run: |
          make build
          sudo install_dir="${install_dir}" make install
          make clean
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 04-as-fp

  five:
    needs: zero
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        generator:
          - { name: Ninja, multi: false }
          - { name: Unix Makefiles, multi: false }
        shared:
          - ON
          - OFF
        flavor:
          - Debug
          - Release
    runs-on: ${{ matrix.platform }}
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: /usr/local
      executable: five
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 05-fetch-content

  six:
    needs: one
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        generator:
          - { name: Ninja, multi: false }
          - { name: Unix Makefiles, multi: false }
        shared:
          - ON
          - OFF
        flavor:
          - Debug
          - Release
    runs-on: ${{ matrix.platform }}
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: /usr/local
      executable: six
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install zero
        working-directory: 00-upstream
        run: |
          make build
          sudo install_dir="${install_dir}" make install
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 06-fp-fc

  seven:
    needs: two
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        generator:
          - { name: Ninja, multi: false }
          - { name: Unix Makefiles, multi: false }
        shared:
          - ON
          - OFF
        flavor:
          - Debug
          - Release
    runs-on: ${{ matrix.platform }}
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: /usr/local
      executable: seven
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: copy zero
        run: |
          cp -r 00-upstream 02-add-subdirectory\external
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 07-as-fc
