name: nix
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu
          - macos
        generator:
          - Ninja
          - Unix Makefiles
        shared:
          - ON
          - OFF
        flavor:
          - release
          - debug
    runs-on: ${{ matrix.platform }}-latest
    env:
      GENERATOR: ${{ matrix.generator }}
      SHARED: ${{ matrix.shared }}
      FLAVOR: ${{ matrix.flavor }}
      install_dir: /usr/local
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install pytest
        run: poetry install
      - name: export cupcake
        uses: ./.github/actions/export-cupcake
      - name: test
        run: poetry run pytest tests/ --builder make
