name: Build, run, test, and install on Linux and MacOS
on: [push, pull_request]

jobs:
  zero:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        generator:
          - { name: Ninja, multi: false }
          - { name: Unix Makefiles, multi: false }
        shared:
          - ON
          - OFF
        flavor:
          - Debug
          - Release
    runs-on: ${{ matrix.platform }}
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: /usr/local
      executable: 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: configure
        working-directory: 00-upstream
        run: make configure
      - name: build
        working-directory: 00-upstream
        run: make build
      - name: built
        working-directory: 00-upstream
        run: make built
      - name: test
        working-directory: 00-upstream
        run: make test
      - name: install
        working-directory: 00-upstream
        run: sudo install_dir="${install_dir}" make install
      - name: installed
        working-directory: 00-upstream
        run: make installed
      - name: path
        run: ${executable}

  one:
    needs: zero
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        generator:
          - { name: Ninja, multi: false }
          - { name: Unix Makefiles, multi: false }
        shared:
          - ON
          - OFF
        flavor:
          - Debug
          - Release
    runs-on: ${{ matrix.platform }}
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: /usr/local
      executable: hello
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install zero
        working-directory: 00-upstream
        run: |
          make build
          sudo install_dir="${install_dir}" make install
      - name: configure
        working-directory: 01-find-package
        run: make configure
      - name: build
        working-directory: 01-find-package
        run: make build
      - name: built
        working-directory: 01-find-package
        run: make built
      - name: install
        working-directory: 01-find-package
        run: sudo install_dir="${install_dir}" make install
      - name: installed
        working-directory: 01-find-package
        run: make installed
      - name: path
        run: ${executable}

  two:
    needs: zero
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        generator:
          - { name: Ninja, multi: false }
          - { name: Unix Makefiles, multi: false }
        shared:
          - ON
          - OFF
        flavor:
          - Debug
          - Release
    runs-on: ${{ matrix.platform }}
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: /usr/local
      executable: goodbye
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: copy zero
        run: |
          mkdir 02-add-subdirectory/external
          cp -r 00-upstream 02-add-subdirectory/external
      - name: configure
        working-directory: 02-add-subdirectory
        run: make configure
      - name: build
        working-directory: 02-add-subdirectory
        run: make build
      - name: built
        working-directory: 02-add-subdirectory
        run: make built
      - name: install
        working-directory: 02-add-subdirectory
        run: sudo install_dir="${install_dir}" make install
      - name: installed
        working-directory: 02-add-subdirectory
        run: make installed
      - name: path
        run: ${executable}

  three:
    needs: one
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        generator:
          - { name: Ninja, multi: false }
          - { name: Unix Makefiles, multi: false }
        shared:
          - ON
          - OFF
        flavor:
          - Debug
          - Release
    runs-on: ${{ matrix.platform }}
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: /usr/local
      executable: aloha
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install zero
        working-directory: 00-upstream
        run: |
          make build
          sudo install_dir="${install_dir}" make install
      - name: install one
        working-directory: 01-upstream
        run: |
          make build
          sudo install_dir="${install_dir}" make install
      - name: configure
        working-directory: 03-fp-fp
        run: make configure
      - name: build
        working-directory: 03-fp-fp
        run: make build
      - name: built
        working-directory: 03-fp-fp
        run: make built
      - name: install
        working-directory: 03-fp-fp
        run: sudo install_dir="${install_dir}" make install
      - name: installed
        working-directory: 03-fp-fp
        run: make installed
      - name: path
        run: ${executable}
