name: nix
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu
          - macos
        cmake:
          - 3.27.x
          - 3.28.x
          - 3.29.x
    runs-on: ${{ matrix.platform }}-latest
    env:
      GENERATOR: 'Unix Makefiles,Ninja'
      SHARED: 'OFF,ON'
      FLAVOR: 'release,debug'
      install_dir: /usr/local
    steps:
      - name: install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: ${{ matrix.cmake }}
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: install environment
        uses: ./.github/actions/install-nix
        with:
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install pytest
        run: poetry install
      - name: export cupcake
        uses: ./.github/actions/export-cupcake
      - name: test
        run: poetry run pytest tests/ --builder make
