name: Build and test on Linux
on: [push, pull_request]

jobs:
  job:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        shared:
          - ON
          - OFF
        flavor:
          - Debug
          - Release
    runs-on: ${{ matrix.platform }}
    steps:
      - name: install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: install environment
        run: |
          pip install conan
          python --version
          conan --version
          cmake --version
          gcc --version
      - name: checkout
        uses: actions/checkout@v2
      - name: configure
        run: cd 00-upstream && make shared=${{ matrix.shared }} flavor=${{ matrix.flavor }} configure
      - name: build
        run: cd 00-upstream && make build
      - name: run
        run: cd 00-upstream && make run
      - name: test
        run: cd 00-upstream && make test
      - name: install
        run: cd 00-upstream && make install
