name: windows
on: [push, pull_request]

jobs:
  _00-upstream:
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install cupcake
        uses: ./.github/actions/install-cupcake
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 00-upstream
          executable: 'true'

  _01-find-package:
    needs: _00-upstream
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install cupcake
        uses: ./.github/actions/install-cupcake
      - name: install 00-upstream
        working-directory: 00-upstream
        run: |
          make install
          make clean
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 01-find-package
          executable: hello
          with-tests: ${{ matrix.shared == 'OFF' }}

  _02-add-subdirectory:
    needs: _00-upstream
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install cupcake
        uses: ./.github/actions/install-cupcake
      - name: copy 00-upstream
        run: |
          cp -r 00-upstream 02-add-subdirectory\external
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 02-add-subdirectory
          executable: goodbye
          with-tests: ${{ matrix.shared == 'OFF' }}

  _03-fp-fp:
    needs: _01-find-package
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install cupcake
        uses: ./.github/actions/install-cupcake
      - name: install 00-upstream
        working-directory: 00-upstream
        run: |
          make install
          make clean
      - name: install 01-find-package
        working-directory: 01-find-package
        run: |
          make install
          make clean
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 03-fp-fp
          executable: aloha
          with-tests: ${{ matrix.shared == 'OFF' }}

  _04-as-fp:
    needs: _02-add-subdirectory
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install cupcake
        uses: ./.github/actions/install-cupcake
      - name: copy 00-upstream
        run: |
          cp -r 00-upstream 02-add-subdirectory\external
      - name: install 02-add-subdirectory
        working-directory: 02-add-subdirectory
        run: |
          make install
          make clean
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 04-as-fp
          executable: four
          with-tests: ${{ matrix.shared == 'OFF' }}

  _05-fetch-content:
    needs: _00-upstream
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install cupcake
        uses: ./.github/actions/install-cupcake
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 05-fetch-content
          executable: five
          with-tests: ${{ matrix.shared == 'OFF' }}

  _06-fp-fc:
    needs: _01-find-package
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install cupcake
        uses: ./.github/actions/install-cupcake
      - name: install 00-upstream
        working-directory: 00-upstream
        run: |
          make install
          make clean
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 06-fp-fc
          executable: six
          with-tests: ${{ matrix.shared == 'OFF' }}

  _07-as-fc:
    needs: _02-add-subdirectory
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install cupcake
        uses: ./.github/actions/install-cupcake
      - name: copy 00-upstream
        run: |
          cp -r 00-upstream 02-add-subdirectory\external
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 07-as-fc
          executable: seven
          with-tests: ${{ matrix.shared == 'OFF' }}

  _08-find-module:
    needs: _00-upstream
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
        zero:
          - missing
          - half
          - full
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install cupcake
        uses: ./.github/actions/install-cupcake
      - name: install zero
        if: matrix.zero != 'missing'
        working-directory: 00-upstream
        run: |
          make install
          make clean
      - name: remove zero configuration
        if: matrix.zero == 'half'
        run: rm -r $env:install_dir\share\zero
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 08-find-module
          executable: eight
          with-tests: ${{ matrix.shared == 'OFF' }}

  _09-external-project:
    needs: _00-upstream
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install cupcake
        uses: ./.github/actions/install-cupcake
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 09-external-project
          executable: nine
          with-tests: ${{ matrix.shared == 'OFF' }}

  _10-conan:
    needs: _00-upstream
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install cupcake
        uses: ./.github/actions/install-cupcake
      - name: export zero
        working-directory: 00-upstream
        run: conan create .
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 10-conan
          executable: ten
          with-tests: ${{ matrix.shared == 'OFF' }}

  _11-no-cupcake:
    needs: _00-upstream
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: export cupcake
        working-directory: cupcake
        run: conan create .
      - name: export zero
        working-directory: 00-upstream
        run: conan create .
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 11-no-cupcake
          executable: eleven
          with-tests: ${{ matrix.shared == 'OFF' }}
