name: Build, run, test, and install on Windows
on: [push, pull_request]

jobs:
  upstream:
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: .\.github\actions\install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: configure
        working-directory: 00-upstream
        run: make configure
      - name: build
        working-directory: 00-upstream
        run: make build
      - name: built
        working-directory: 00-upstream
        run: make built
      - name: test
        working-directory: 00-upstream
        run: make test
      - name: install
        working-directory: 00-upstream
        run: make install
      - name: installed
        working-directory: 00-upstream
        run: make installed
      - name: path
        run: $env:PATH = "C:\\bin;$env:PATH"; executable

  find-package:
    needs: upstream
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: .\.github\actions\install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install
        working-directory: 00-upstream
        run: make install
      - name: configure
        working-directory: 01-find-package
        run: make configure
      - name: build
        working-directory: 01-find-package
        run: make build
      - name: built
        if: matrix.shared == 'OFF'
        working-directory: 01-find-package
        run: make built
      - name: install
        working-directory: 01-find-package
        run: make install
      - name: installed
        working-directory: 01-find-package
        run: make installed
      - name: path
        run: $env:PATH = "C:\\bin;$env:PATH"; executable
