name: Build, run, test, and install on Windows
on: [push, pull_request]

jobs:
  zero:
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
      executable: 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: configure
        working-directory: 00-upstream
        run: make configure
      - name: build
        working-directory: 00-upstream
        run: make build
      - name: built
        working-directory: 00-upstream
        run: make built
      - name: test
        working-directory: 00-upstream
        run: make test
      - name: install
        working-directory: 00-upstream
        run: |
          make install
          make clean
      - name: installed
        working-directory: 00-upstream
        run: make installed
      - name: path
        run: $env:PATH = "C:\\bin;$env:PATH"; $env:executable

  one:
    needs: zero
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
      executable: hello
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install zero
        working-directory: 00-upstream
        run: |
          make install
          make clean
      - name: configure
        working-directory: 01-find-package
        run: make configure
      - name: build
        working-directory: 01-find-package
        run: make build
      # We cannot test the executable in the build directory until it is
      # installed next to the shared libraries that it requires.
      - name: built
        if: matrix.shared == 'OFF'
        working-directory: 01-find-package
        run: make built
      - name: test
        if: matrix.shared == 'OFF'
        working-directory: 01-find-package
        run: make test
      - name: install
        working-directory: 01-find-package
        run: |
          make install
          make clean
      - name: installed
        working-directory: 01-find-package
        run: make installed
      - name: path
        run: $env:PATH = "C:\\bin;$env:PATH"; $env:executable

  two:
    needs: zero
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
      executable: goodbye
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: copy zero
        run: |
          mkdir 02-add-subdirectory\external
          cp -r 00-upstream 02-add-subdirectory\external
      - name: configure
        working-directory: 02-add-subdirectory
        run: make configure
      - name: build
        working-directory: 02-add-subdirectory
        run: make build
      - name: built
        working-directory: 02-add-subdirectory
        run: make built
      - name: test
        if: matrix.shared == 'OFF'
        working-directory: 02-add-subdirectory
        run: make test
      - name: install
        working-directory: 02-add-subdirectory
        run: |
          make install
          make clean
      - name: installed
        working-directory: 02-add-subdirectory
        run: make installed
      - name: path
        run: $env:PATH = "C:\\bin;$env:PATH"; $env:executable

  three:
    needs: one
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
      executable: aloha
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install zero
        working-directory: 00-upstream
        run: |
          make install
          make clean
      - name: install one
        working-directory: 01-find-package
        run: |
          make install
          make clean
      - name: configure
        working-directory: 03-fp-fp
        run: make configure
      - name: build
        working-directory: 03-fp-fp
        run: make build
      - name: built
        if: matrix.shared == 'OFF'
        working-directory: 03-fp-fp
        run: make built
      - name: test
        if: matrix.shared == 'OFF'
        working-directory: 03-fp-fp
        run: make test
      - name: install
        working-directory: 03-fp-fp
        run: |
          make install
          make clean
      - name: installed
        working-directory: 03-fp-fp
        run: make installed
      - name: path
        run: $env:PATH = "C:\\bin;$env:PATH"; $env:executable
