name: windows
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        generator:
          - Visual Studio 16 2019
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      GENERATOR: ${{ matrix.generator }}
      SHARED: ${{ matrix.shared }}
      FLAVOR: ${{ matrix.flavor }}
      install_dir: C:\\
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install pytest
        run: poetry install
      - name: export cupcake
        uses: ./.github/actions/export-cupcake
      - name: test
        run: poetry run pytest
