name: windows
on: [push, pull_request]

jobs:
  zero:
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
      executable: 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 00-upstream

  one:
    needs: zero
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
      executable: hello
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install zero
        working-directory: 00-upstream
        run: |
          make install
          make clean
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 01-find-package
          with-tests: ${{ matrix.shared == 'OFF' }}

  two:
    needs: zero
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
      executable: goodbye
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: copy zero
        run: |
          cp -r 00-upstream 02-add-subdirectory\external
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 02-add-subdirectory
          with-tests: ${{ matrix.shared == 'OFF' }}

  three:
    needs: one
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
      executable: aloha
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install zero
        working-directory: 00-upstream
        run: |
          make install
          make clean
      - name: install one
        working-directory: 01-find-package
        run: |
          make install
          make clean
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 03-fp-fp
          with-tests: ${{ matrix.shared == 'OFF' }}

  four:
    needs: two
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
      executable: four
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: copy zero
        run: |
          cp -r 00-upstream 02-add-subdirectory\external
      - name: install two
        working-directory: 02-add-subdirectory
        run: |
          make install
          make clean
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 04-as-fp
          with-tests: ${{ matrix.shared == 'OFF' }}

  five:
    needs: zero
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
      executable: five
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 05-fetch-content
          with-tests: ${{ matrix.shared == 'OFF' }}

  six:
    needs: one
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
      executable: six
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install zero
        working-directory: 00-upstream
        run: |
          make install
          make clean
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 06-fp-fc
          with-tests: ${{ matrix.shared == 'OFF' }}

  seven:
    needs: two
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
      executable: seven
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: copy zero
        run: |
          cp -r 00-upstream 02-add-subdirectory\external
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 07-as-fc
          with-tests: ${{ matrix.shared == 'OFF' }}

  eight:
    needs: zero
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
        zero:
          - missing
          - half
          - full
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
      executable: eight
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: install zero
        if: matrix.zero != 'missing'
        working-directory: 00-upstream
        run: |
          make install
          make clean
      - name: remove zero configuration
        if: matrix.zero == 'half'
        run: rm -r $env:install_dir\lib\cmake\zero
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 08-find-module
          with-tests: ${{ matrix.shared == 'OFF' }}

  nine:
    needs: zero
    strategy:
      matrix:
        generator:
          - { name: Visual Studio 16 2019, multi: true }
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator.name }}
      multi: ${{ matrix.generator.multi && 'true' || '' }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
      executable: nine
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install environment
        uses: ./.github/actions/install-windows
        with:
          cache-key-scoop: ${{ secrets.CACHE_SCOOP }}
          cache-key-python: ${{ secrets.CACHE_PYTHON }}
      - name: test project
        uses: ./.github/actions/test-project
        with:
          working-directory: 09-external-project
          with-tests: ${{ matrix.shared == 'OFF' }}
