name: Build, run, test, and install on Windows
on: [push, pull_request]

jobs:
  job:
    strategy:
      matrix:
        generator:
          - Visual Studio 16 2019
        shared:
          - OFF
          - ON
        flavor:
          - Debug
          - Release
    runs-on: windows-2019
    env:
      generator: ${{ matrix.generator }}
      shared: ${{ matrix.shared }}
      flavor: ${{ matrix.flavor }}
      install_dir: C:\\
    steps:
      - name: install tools
        run: |
          iwr -useb get.scoop.sh | iex
          scoop install make
          pip install conan
      - name: check environment
        run: |
          $env:PATH -split ';'
          python --version
          conan --version
          cmake --version
          make --version
          dir env:
      - name: checkout
        uses: actions/checkout@v2
      - name: configure
        working-directory: 00-upstream
        run: make configure
      - name: build
        working-directory: 00-upstream
        run: make build
      - name: built
        working-directory: 00-upstream
        run: make built
      - name: test
        working-directory: 00-upstream
        run: make test
      - name: install
        working-directory: 00-upstream
        run: make install
      - name: installed
        working-directory: 00-upstream
        run: make installed
      - name: path
        run: $env:PATH = "C:\\bin;$env:PATH"; executable
